export const FETCH_BUBBLE_INFO_SUCCESS = 'FETCH_BUBBLE_INFO_SUCCESS';
export const FETCH_BUBBLE_INFO_ERROR = 'FETCH_BUBBLE_INFO_ERROR';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_ERROR = 'SUBMIT_ANSWER_ERROR';